### ISSUE TITLE
[Bug] Adding new attribute with the + menu, clicking on suggested text doesn't update the real attribute name/value when saving

### ISSUE THREAD

**Issue by Grymas** [zadam/trilium#1557]
Version 0.45.8, on Kubuntu using the .deb release

When I add an attribute (label or relation) with the "+" menu to the right, selecting suggested text (such as a previously used label showing after typing the first characters) with the mouse doesn't truly update the name or value of the attribute.
When saving, the only name/value saved is the few characters that were typed before clicking on the suggested text, so attributes have to be manually typed to save properly.

In this example, I typed "e" and clicked on the suggested text "event", but the value of the attribute before saving is still #e
![image](https://user-images.githubusercontent.com/12102823/105373294-d3542b80-5c06-11eb-9e5f-e36b793d56e9.png)

The name or value only updates when filling another field or typing directly into the field.

**Comment by zadam** [comment]
Thanks for reporting this issue, it has been fixed in stable branch.

**Comment by Grymas** [comment]
Still have this problem on the latest update, selecting a suggested name for the title or value of an attribute seems to fill the text box, but the value isn't really updated unless something is typed in the field (even just a space), so selecting the suggested value then CTRL+Enter or saving doesn't have the intended result and saves only the few characters typed before selecting the suggested value.

**Comment by zadam** [comment]
Hi, so I didn't realize this affects also value autocomplete and fixed previously only name. Now it should be fixed for both.
