### ISSUE TITLE
Moving node in Firefox using CTRL+UP/DOWN shortcut doesn't work as expected.

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#1865]
Version: 0.45.10
Browser: Firefox
Note: This issue only seems to manifest in Firefox

When using the CTRL+UP or CTRL+DOWN keyboard shortcuts to move a node/note up or down the tree, it will work for the first time I press the UP/DOWN key, but after that it's like Firefox looses focus of the selected node and pressing UP/DOWN again doesn't do anything until i re-select the node.

Perhaps this is something that would require a change in Firefox, but i wanted to report it anyway in case someone else finds a work-around.

**Comment by zadam** [comment]
Hi, I think it's a focusing issue which was fixed in 0.46. So upgrading to latest stable should help.

**Comment by WPum** [comment]
I test it in 0.46.7 and the problem still exists. I can only move a note up/down once without clicking the note again.

**Comment by meichthys** [comment]
I've also updated to 0.46.7 and still seem to experience the loss of focus after moving the node once.

**Comment by zadam** [comment]
Ok, I admit I overlooked/ignored the Firefox mention - indeed I can reproduce the issue on Firefox but not elsewhere. I will look into this.

**Comment by zadam** [comment]
fixed in stable branch, will be in 0.46.8
