### ISSUE TITLE
Bug: Changing tabs in zen mode breaks UI

### ISSUE THREAD

**Issue by surajsharma** [zadam/trilium#2015]
Version: 0.47.2
OS: macOS Catalina 10.15.7 (19H1217)

[Latest Log](https://pastebin.com/NKfDfPm2)

Description to reproduce: 
1) Enter zen mode on any note
2) Switch to a different note (tab)
3) UI is misaligned 

demo:
![demo](https://puu.sh/HOkDv/2504c89231.gif)

**Comment by zadam** [comment]
Hi, this was fixed recently, just upgrade to 0.47.4.

**Comment by surajsharma** [comment]
not fixed on firefox for me, kindly check? i am running an updated fork

**Comment by zadam** [comment]
Hi, yes, just tested on firefox 89, zen mode works fine while switching tabs.
