### ISSUE TITLE
(Bug report) Can't open Trilium

### ISSUE THREAD

**Issue by dairrrj** [zadam/trilium#3068]
### Trilium Version

0.50.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

windows10 19041.1415

### Description

Trilium's window is white and unusable when I open the software, rebooting computer is also not working. I also installed newest version 0.54.2, but the same issue happened. 
![Snipaste_2022-08-17_11-22-52](https://user-images.githubusercontent.com/36892458/185028066-7294067c-3223-482b-9252-0be389ba8d26.jpg)

**Comment by Lewiscowles1986** [comment]
This can happen when the database becomes corrupt or has a value which causes frontend error.

I was recommended safe-mode startup (see the wiki), but also a fix was released, which I just ensured was on my local, and everything worked.

What were you doing when this broke?

**Comment by zadam** [comment]
Hi, can you run trilium from command prompt to see if there are any fatal error messages and post those here? Thanks.

**Comment by dairrrj** [comment]
> Hi, can you run trilium from command prompt to see if there are any fatal error messages and post those here? Thanks.
./
Hi! The error messages are posted below. I also tried https://github.com/zadam/trilium/issues/2071 this solution, and it works. But still can't open it by click trilium.exe icon. If there is a way I can open Trilium normally by click icon?  Thank you!

DB size: 3223 KB
Becca (note cache) load took 18ms
Trusted reverse proxy: false
App HTTP server starting up at port 37840
{
  "appVersion": "0.54.2",
  "dbVersion": 197,
  "syncVersion": 26,
  "buildDate": "2022-08-07T23:20:59+02:00",
  "buildRevision": "3a07c5fcc059019a2330a3f6ed204eeb5df1539d",
  "dataDirectory": "C:\\Users\\290669\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2022-08-20T06:05:18.275Z"
}
CPU model: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, logical cores: 8 freq: 2803 Mhz
Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
Listening on port 37840
Generated CSRF token NE8uZaLG-qNjTpOGfY7VD42qKb0aXmtwpcYQ with secret _csrf=2Crm4nE3mDns3-LeD6P15gtn; Path=/
[23068:0820/140522.098:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
Table counts: notes: 280, note_revisions: 143, branches: 298, attributes: 285, etapi_tokens: 0
All consistency checks passed with no errors detected (took 35ms)
[23068:0820/140524.188:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[23068:0820/140526.249:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[23068:0820/140528.316:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[23068:0820/140530.392:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[23068:0820/140532.466:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819

**Comment by dairrrj** [comment]
> This can happen when the database becomes corrupt or has a value which causes frontend error.
> 
> I was recommended safe-mode startup (see the wiki), but also a fix was released, which I just ensured was on my local, and everything worked.
> 
> What were you doing when this broke?

Thank you! But safe-mode startup seems not working, still have gpu error. I maybe shut down computer without closed trilium window(can't remember clearly), then this broke happened when I reopened trilium the next day. 

DB size: 3223 KB
Becca (note cache) load took 5ms
Trusted reverse proxy: false
App HTTP server starting up at port 37840
{
  "appVersion": "0.54.2",
  "dbVersion": 197,
  "syncVersion": 26,
  "buildDate": "2022-08-07T23:20:59+02:00",
  "buildRevision": "3a07c5fcc059019a2330a3f6ed204eeb5df1539d",
  "dataDirectory": "C:\\Users\\290669\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2022-08-20T06:39:02.471Z"
}
CPU model: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, logical cores: 8 freq: 2803 Mhz
Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
Listening on port 37840
Generated CSRF token 7wNRInFT-LyvA9VpAjFgexIuVqIT-ckHNp_M with secret _csrf=_FChMyEgOw1ESuK-vV3_rs9n; Path=/
[10644:0820/143906.166:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
Table counts: notes: 280, note_revisions: 143, branches: 298, attributes: 285, etapi_tokens: 0
All consistency checks passed with no errors detected (took 8ms)
[10644:0820/143908.234:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[10644:0820/143910.305:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[10644:0820/143912.380:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[10644:0820/143914.432:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819
[10644:0820/143916.499:ERROR:gpu_process_host.cc(968)] GPU process exited unexpectedly: exit_code=-1073741819

**Comment by zadam** [comment]
Yep, so it's clearly a GPU (driver) problem, and the app has to be started as `./trilium --disable-gpu`. You can create a shortcut which runs this command for you or possibly just trivial `.bat` script.

**Comment by dairrrj** [comment]
Thank you! @zadam , I will try these.
