### ISSUE TITLE
Version 0.61 has been in the BETA phase for several months!

### ISSUE THREAD

**Issue by Magla0** [zadam/trilium#4331]
### Describe feature

Hello, why v0.61 is still not released?
 I think there are a lot of people like me waiting for this version!

**Comment by rauenzi** [comment]
There are still bugs being fixed with a focus on resolving sync issues. There is a significant change to the way some note resources like images are handled so it's important to have any related bugs fixed before it gets released as "stable".

**Comment by Magla0** [comment]
All right.  Thank you for the information.  But for the moment I don't use trilium because of the attachments which use new notes when they should be integrated into the main note.  That's why I'm impatiently waiting for version 0.61.

 What is the estimated release date for this version?

**Comment by zadam** [comment]
GIMP 2.99 / 3.0 has been in beta for 3 years (still not released), I hope we'll be faster than that with 0.61.

As somebody mentioned, I'm trying to iron out the sync issues before a stable release. I will be releasing a new beta soon, if those sync fixes prove to be sufficient, then the stable won't take much more time.

**Comment by bmcgonag** [comment]
Just to say it, since it wasn't said in the start of this issue as it should have been, thank you @zadam and @deajan for this awesome project.  And thank you for all the time and care you're giving it.

**Comment by deajan** [comment]
It's all on @zadam, I only hang around github a bit since I use trilium intensively.

**Comment by Joackk** [comment]
I'm also looking forward to the official release of version 61.0. However, as mentioned above, the synchronization issue is the biggest challenge affecting the release of the official version. So perhaps we should patiently wait for a while. Otherwise, if there are problems with synchronization, it could be very troublesome, don't you think?

**Comment by rom1dep** [comment]
@eliandoran safe to close?

**Comment by eliandoran** [comment]
@rom1dep , absolutely.
