### ISSUE TITLE
[Feature Request] Improved book print

### ISSUE THREAD

**Issue by Karol-G** [zadam/trilium#899]
App Version: 0.40.4

Hi,

when printing a node as pdf that is of type book then the pdf does not look anywhere as nice as in trilium. All of the nice gray bounding boxes (don't know how they are called) go missing and all of the node hierachy too. I don't know if the print functionality for books is currently broken, but in the best case the pdf should look just like in trilium.

How it looks in trilium:
![Unbenannt](https://user-images.githubusercontent.com/3471895/76110226-6c258c80-5fde-11ea-89cc-ea50bb19a25e.PNG)

How it looks as pdf:
![Unbenannt](https://user-images.githubusercontent.com/3471895/76110166-4a2c0a00-5fde-11ea-94d9-fcd7e529e843.PNG)

Best
Karol

**Comment by zadam** [comment]
Hello, this was fixed. It does not look exactly the same - e.g. background color is ignored in PDF (I assume to conserve ink), but borders are now rendered with indentation so that the tree structure is visible.

**Comment by Karol-G** [comment]
Cool thanks!

**Comment by Karol-G** [comment]
Thanks again for the fix, but it seems to be still buggy. Only child nodes get borders, but not the top nodes.
Version: 0.40.5

![grafik](https://user-images.githubusercontent.com/3471895/76417215-c5a20880-639c-11ea-9b26-f7fef8294f61.png)
